version: '3'


services:

  #*******************************************************#
  # * Nast Server : Transports (Servicio de Mensajeria) * #
  #*******************************************************#

  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"
    
#*******************************************************#
  # * Client Gategay : API Resfull (Https) *            #
#*******************************************************#

  client-gateway:
    depends_on:
     - nats-server
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      
  #*******************************************************#
  # * Auth  : MS Auth-ms (Guard y JWT)                    #
  #*******************************************************#
  
  auth-ms:
    depends_on:
     - nats-server
    build: ./auth-ms
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222     
      - DATABASE_URL=${AUTH_DATABASE_URL}  
      - JWT_SECRET=${JWT_SECRET}

#*******************************************************#
# * Payments  : MS Payments-ms (Stripe)                 #
#*******************************************************#
  payments-ms:
    depends_on:
     - nats-server
    build: ./payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:3003
    
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NODE_ENV=${NODE_ENV}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCER_URL=${STRIPE_CANCER_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - NATS_SERVERS=nats://nats-server:4222  

  #*******************************************************#
  # * Products  : MS products-ms (Stripe)                 #
  #*******************************************************#
  products-ms:
    depends_on:
      - nats-server
    build: ./products-ms
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - DATABASE_URL='file:./dev.db'
      - NATS_SERVERS=nats://nats-server:4222

#*******************************************************#
# * Order  : MS Order BDD Postgres (Not Https) *     #
#*******************************************************#
  orders-ms:
    depends_on:
      - orders-db
      - nats-server
    build: ./orders-ms
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/ordersdb?schema=public
      - NATS_SERVERS=nats://nats-server:4222

#*******************************************************#
# * Postgres  : BDD Postgres para Ordenes *                  #
#*******************************************************#
  orders-db:
    container_name: orders_database
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersdb
    